### ISSUE TITLE
Golink fails when proto file imports other protos

### ISSUE THREAD

**Issue by luna-duclos** [nikunjy/golink#1]
Hello!

I recently tried this tool out on Embark's internal bazel repo and we noticed golink seems to generate faulty rules when dealing with a proto file with dependencies.

For example, for the following bazel rule file, you can see that the go_proto_link rule is refering to a go_proto_library that does not actually exist in this package:

```python
load("@golink//proto:proto.bzl", "go_proto_link")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "inventory_proto",
    srcs = ["inventory_user.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//services/online-subsystem/proto/inventory/inventory:inventory_proto",
        "@go_googleapis//google/rpc:status_proto",
    ],
)

go_proto_library(
    name = "inventory_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "github.com/EmbarkStudios/src/services/online-subsystem/proto/inventory/user",
    proto = ":user_proto",
    visibility = ["//visibility:public"],
    deps = ["//services/online-subsystem/proto/inventory/inventory:go_default_library"],
)

go_library(
    name = "go_default_library",
    embed = [":inventory_go_proto"],
    importpath = "github.com/EmbarkStudios/src/services/online-subsystem/proto/inventory/user",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "user_proto",
    srcs = ["inventory_user.proto"],
    visibility = ["//visibility:public"],
    deps = ["//services/online-subsystem/proto/inventory/inventory:inventory_proto"],
)

go_proto_link(
    name = "user_go_proto_link",
    dep = ":user_go_proto",
    version = "v1",
)
```

**Comment by nikunjy** [comment]
Hey @luna-duclos  sorry have been away for a while. 
It is little bit weird that you don't have a `go_proto_library` for `user_proto` you should. There is nothing hardcoded in my library that should generate this target like this. 
I would need to understand a little bit more, were the targets generated by gazelle? Did you change them manually?

I tested this in my own test repo in this commit and it seems to work 
https://github.com/nikunjy/go/commit/77b1979603fb05050916f4f104a43585431336cb#diff-b5c7df0248b51c12d89d55f919c29bc4

**Comment by luna-duclos** [comment]
The targets were indeed generated by gazelle, this happens when you have protos in two different directories and seperate BUILD.bazel files are generated for them and set to depend on eachother.
Let me know if you have any trouble reproducing it and I can work on making an example and posting it here.

**Comment by nikunjy** [comment]
Here is an example with two different directories and two different `BUILD.bazel` 
https://github.com/nikunjy/go/commit/e6ce5a2b60a5b119e7334d6e689aab7d9966d641

I have a `hello` package and a `common` package. `hello` imports from `common` but I am not seeing the same problem. 

It seems like your directory structure is like this 
```
|-inventory
|--inventory
|---BUILD.bazel (declares inventory_proto)
|--user
|---BUILD.bazel (one you have copied here)
|---inventory_user.proto
```
Also there are two targets that are building the same thing `inventory_proto` and `user_proto` but `inventory_go_proto` depends only on `user_proto`. This seems a little odd. Would be great to have a minimalistic example for your problem.

**Comment by luna-duclos** [comment]
Will make one and make a gist!

**Comment by nikunjy** [comment]
any luck @luna-duclos ?

**Comment by luna-duclos** [comment]
The issue was on our end! I apologize for taking so long to get back to you, I've been quite swarmed.

**Comment by nikunjy** [comment]
Glad to know you figured it out and it worked for you @luna-duclos 
Let me know if you think of other improvements in this lib.
